const telegram = "https://t.me/Gencou_bot";

const benefits = [
  ["Rule-based participation", "Automated systems follow predefined conditions instead of reacting impulsively to every candle, headline or temporary market move."],
  ["Consistent execution", "An Expert Advisor can monitor eligible opportunities, apply configured position rules and execute without requiring the trader to remain in front of a screen."],
  ["Structured risk controls", "Trade size, stop-loss logic, exposure limits, trading hours and daily safeguards can be built into the strategy configuration."],
  ["Measurable decisions", "Automated trading creates records that can be reviewed, tested and improved instead of relying on memory, instinct or emotional interpretation."],
];

const profiles = [
  { name: "Gencouv Core", label: "Measured participation", description: "Designed for clients who prefer more controlled market exposure, lower strategy intensity and a steadier automation framework.", items: ["Systematic execution", "Defined risk parameters", "Broker-platform monitoring"], start: "core_profile" },
  { name: "Gencouv Alpha", label: "Higher-intensity participation", description: "Designed for experienced clients who understand that increased opportunity frequency can also produce larger fluctuations and drawdowns.", items: ["Automated execution", "Higher market activity", "Enhanced risk awareness required"], start: "alpha_profile" },
];

export default function Home() {
  return <main>
    <nav className="nav shell">
      <a className="brand" href="/"><span>G</span><div><b>GENCOUV</b><small>AI TRADING TECHNOLOGY</small></div></a>
      <div className="links"><a href="/about">About</a><a href="#education">Why automation</a><a href="/marketplace">Marketplace</a><a href="/testimonials">Testimonials</a><a href="/terms">Terms</a></div>
      <a className="navCta" href={`${telegram}?start=website`} target="_blank" rel="noreferrer">Begin onboarding</a>
    </nav>

    <section className="hero shell">
      <div className="eyebrow">AI-ASSISTED & AUTOMATED MARKET PARTICIPATION</div>
      <h1>Trade with systems.<br/><em>Not shifting emotions.</em></h1>
      <p>Gencouv provides automated trading solutions, Expert Advisors, indicators and guided onboarding for clients who want a more structured way to participate in financial markets.</p>
      <div className="heroActions"><a className="primary" href={`${telegram}?start=automation_onboarding`} target="_blank" rel="noreferrer">Explore automated trading <span>↗</span></a><a className="secondary" href="#education">Learn how it works</a></div>
      <div className="trust"><span>Systematic execution</span><span>Configurable risk controls</span><span>Continuous monitoring</span><span>Human-guided onboarding</span></div>
      <div className="terminal"><div className="terminalTop"><div className="brand mini"><span>G</span><div><b>GENCOUV</b><small>AUTOMATION CONTROL</small></div></div><div className="online"><i/>SYSTEM ONLINE</div></div><div className="terminalGrid"><aside><b>Workspace</b><span className="active">Automation</span><span>Strategies</span><span>Risk Engine</span><span>Executions</span><span>Reports</span></aside><div className="chartArea"><div className="chartHead"><div><small>Illustrative strategy activity</small><strong>24/5 Monitoring</strong></div><span>ACTIVE</span></div><div className="chart"><div className="gridlines"/><svg viewBox="0 0 800 260" role="img" aria-label="Illustrative strategy activity"><path className="area" d="M0 220 C70 210 100 185 155 192 S245 150 300 165 S390 118 455 130 S550 90 610 104 S710 55 800 72 L800 260 L0 260 Z"/><path className="line" d="M0 220 C70 210 100 185 155 192 S245 150 300 165 S390 118 455 130 S550 90 610 104 S710 55 800 72"/></svg></div><div className="chartMeta"><span>Execution <b>Rule-based</b></span><span>Monitoring <b>Continuous</b></span><span>Controls <b>Configured</b></span></div></div><div className="metrics"><article><small>Decision model</small><strong>Systematic</strong><span>Rules before reactions</span></article><article><small>Market access</small><strong>Automated</strong><span>Configured participation</span></article><article><small>Review process</small><strong>Trackable</strong><span>Data-led evaluation</span></article></div></div></div>
    </section>

    <section id="education" className="section shell"><div className="sectionHead"><div><div className="eyebrow left">WHY AUTOMATED TRADING</div><h2>Automation turns a trading plan into repeatable execution.</h2></div><p>It does not remove market risk or guarantee profit. Its value is discipline: monitoring conditions, applying rules and reducing avoidable decision errors caused by fear, greed, hesitation and overtrading.</p></div><div className="knowledgeGrid">{benefits.map(([title,description],i)=><article className="knowledgeCard" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>

    <section className="band"><div className="shell split"><div><div className="eyebrow left">HOW AN EA WORKS</div><h2>A strategy becomes executable software.</h2><p className="lead">An Expert Advisor, commonly called an EA, is software that operates within a compatible trading platform such as MetaTrader 5. It observes market data and responds when its programmed conditions are met.</p></div><div className="steps"><article><span>01</span><div><h3>Market observation</h3><p>The EA continuously checks price, time, volatility or indicator conditions defined by its strategy.</p></div></article><article><span>02</span><div><h3>Rule validation</h3><p>Before acting, it confirms that entry, exposure and risk conditions match the configured logic.</p></div></article><article><span>03</span><div><h3>Execution and management</h3><p>When conditions qualify, the system can place, manage or close trades according to its programmed rules.</p></div></article></div></div></section>

    <section className="section shell"><div className="sectionHead"><div><div className="eyebrow left">AUTOMATION PROFILES</div><h2>Choose an approach that matches your tolerance.</h2></div><p>Suitability matters more than excitement. Every client should understand expected fluctuations, strategy limits and the possibility of loss before activation.</p></div><div className="profileGrid">{profiles.map(p=><article className="profile" key={p.name}><small>{p.label}</small><h3>{p.name}</h3><p>{p.description}</p><div>{p.items.map(x=><span key={x}>✓ {x}</span>)}</div><a href={`${telegram}?start=${p.start}`} target="_blank" rel="noreferrer">Review profile <b>↗</b></a></article>)}</div></section>

    <section className="section shell"><div className="sectionHead"><div><div className="eyebrow left">GENCOUV MARKETPLACE</div><h2>Tools built for systematic participation.</h2></div><p>Browse Expert Advisors, market indicators and trading utilities with clear explanations of their role, configuration and intended user.</p></div><div className="serviceGrid"><a className="service" href="/marketplace"><span>01</span><h3>Expert Advisors</h3><p>Automated strategies for compatible MetaTrader environments, with defined execution and risk parameters.</p><b>Browse EAs ↗</b></a><a className="service" href="/marketplace"><span>02</span><h3>AI-assisted indicators</h3><p>Decision-support tools that help identify structure, momentum, liquidity and changing market conditions.</p><b>Browse indicators ↗</b></a><a className="service" href="/marketplace"><span>03</span><h3>Trading utilities</h3><p>Position-sizing, journaling and analysis tools that improve process quality and accountability.</p><b>Explore utilities ↗</b></a></div></section>

    <section className="risk"><div className="shell riskGrid"><div><div className="eyebrow left">RISK & RESPONSIBILITY</div><h2>Automation improves process, not certainty.</h2></div><p>All trading systems can experience losses, drawdowns, execution differences and periods when market conditions do not favour their logic. Clients remain responsible for understanding the product, selecting appropriate risk settings and monitoring their trading account.</p></div></section>

    <section className="finalCta shell"><div className="eyebrow">GUIDED ONBOARDING</div><h2>Understand the system before activating it.</h2><p>The Gencouv Telegram assistant explains available solutions, asks suitability questions and helps you identify the automation route that fits your experience and objectives.</p><a className="primary" href={`${telegram}?start=website_final`} target="_blank" rel="noreferrer">Begin onboarding <span>↗</span></a></section>

    <footer className="footer shell"><div className="brand"><span>G</span><div><b>GENCOUV</b><small>AI TRADING TECHNOLOGY</small></div></div><p>Automated trading systems, Expert Advisors and market intelligence tools.</p><div><a href="mailto:support@gencouv.com">support@gencouv.com</a><a href="/terms">Terms</a></div><small>© 2026 Gencouv. Trading involves substantial risk. Automated systems do not guarantee profit, and historical performance does not guarantee future results.</small></footer>
  </main>;
}